# Generated by Django 4.2.3 on 2023-07-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['travel_times'], 'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
    ]
